### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by Katletos** [blackhorse-one/stomp_dart_client#101]
Is it possible to use library with self signed? Or how I can pass a certificate in StompClient like http client

`flutter: HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: self signed certificate(handshake.cc:393))`
	
```dart
final client = await _getSSLPinningClient();
locator.registerSingleton<InterceptedClient>(InterceptedClient.build(
    client: client,
    interceptors: [
        LoggingInterceptor(storage: locator.get<SecureStorage>())
    ]));
 ```

**Comment by KammererTob** [comment]
I will close this issue due to inactivity. If you still need assistance feel free to reopen.
