### ISSUE TITLE
Flutter Web Bearer authorization

### ISSUE THREAD

**Issue by TarasBounty** [blackhorse-one/stomp_dart_client#103]
I have a server written on Java.
The client code looks like

`import 'package:stomp_dart_client/stomp_dart_client.dart';
          
          void onConnect(StompFrame frame) {
           pint('connected!')
          }
          
          final stompClient = StompClient(
            config: StompConfig(
              url: 'wss://mynotificationservice/ws',
              onConnect: onConnect,
               stompConnectHeaders: {
                 'Authorization': 'Bearer $_yourToken',
               },
               webSocketConnectHeaders: {
                 'Authorization': 'Bearer $_yourToken',
               },
            ),
          );
          
          void main() async {
            stompClient.activate();
          }
`

Flutter Android works perfectly, but the web throws an unauthorized exception.
If I remove auth logic from the server, the Web starts to work.

**Comment by 1kazakvadim** [comment]
The same problem

**Comment by KammererTob** [comment]
Hi,

probably because your server uses the `webSocketConnectHeaders`, which is not supported in web. See [here](https://github.com/blackhorse-one/stomp_dart_client/issues/90) and [here](https://github.com/blackhorse-one/stomp_dart_client?tab=readme-ov-file#token-authentication-browser-based-clients)

**Comment by 1kazakvadim** [comment]
> Hi,
> 
> probably because your server uses the `webSocketConnectHeaders`, which is not supported in web. See [here](https://github.com/blackhorse-one/stomp_dart_client/issues/90) and [here](https://github.com/blackhorse-one/stomp_dart_client?tab=readme-ov-file#token-authentication-browser-based-clients)

I have such configuration now. For case when I add Authorization header with valid or invalid bearer token it works. But now I have a problem, that it`s possible to connect to web socket without Authorization header. 

    @Override
    public void configureClientInboundChannel(ChannelRegistration registration) {
        registration.interceptors(new ChannelInterceptor() {
            @Override
            public Message<?> preSend(Message<?> message, MessageChannel channel) {
                StompHeaderAccessor accessor = MessageHeaderAccessor.getAccessor(message, StompHeaderAccessor.class);

                if (accessor != null && SimpMessageType.CONNECT.equals(accessor.getMessageType())) {
                    String authToken = accessor.getFirstNativeHeader("Authorization");

                    if (StringUtils.isNotBlank(authToken)) {
                        try {
                            // Validate the token and set the authentication in the context
                            KeycloakAuthenticationToken authentication = keycloakTokenService.validateToken(TokenHelper.getToken(authToken));
                            SecurityContextHolder.getContext().setAuthentication(authentication);
                        } catch (Exception e) {
                            String msg = "Invalid Bearer token for websocket request";
                            log.error(msg, e);
                            sendErrorMessageAndDisconnect(accessor, msg);
                            return null;
                        }
                    } else {
                        String msg = "Missing Authorization header for websocket request";
                        log.error(msg);
                        sendErrorMessageAndDisconnect(accessor, msg);
                        return null;
                    }
                }

                return message;
            }
        });
    }

    private void sendErrorMessageAndDisconnect(StompHeaderAccessor accessor, String errorMessage) {
        Map<String, Object> sessionAttributes = accessor.getSessionAttributes();
        if (sessionAttributes == null) {
            sessionAttributes = new HashMap<>();
            accessor.setSessionAttributes(sessionAttributes);
        }

        sessionAttributes.put("disconnect", true);
        sessionAttributes.put("errorMessage", errorMessage);
    }
    
    Any suggestions how it can be solved?

**Comment by KammererTob** [comment]
You can connect via WebSocket, yes. But you can't do the handshake for STOMP without a valid token (that is what your preSend is checking). 
If you have concerns about unauthed **pure** WebSocket connections i would suggest to move the token to a query parameter in the WebSocket connect URL.

**Comment by TarasBounty** [comment]
We implemented it that way  
> move the token to a query parameter in the WebSocket connect URL.

Thank you so much, I close the ticket

**Comment by 1kazakvadim** [comment]
> You can connect via WebSocket, yes. But you can't do the handshake for STOMP without a valid token (that is what your preSend is checking). If you have concerns about unauthed **pure** WebSocket connections i would suggest to move the token to a query parameter in the WebSocket connect URL.

One more question pls. Is it possible to send UNSUBSCRIBE message from client side?

**Comment by KammererTob** [comment]
@1kazakvadim Yes. See here: https://github.com/blackhorse-one/stomp_dart_client?tab=readme-ov-file#unsubscribe
Or did you mean something else? This function unsubscribes and sends UNSUBSCRIBE to the server.

**Comment by 1kazakvadim** [comment]
> @1kazakvadim Yes. See here: https://github.com/blackhorse-one/stomp_dart_client?tab=readme-ov-file#unsubscribe Or did you mean something else? This function unsubscribes and sends UNSUBSCRIBE to the server.

Thanks, it`s that i means
