### ISSUE TITLE
the callback in Stomp.dart is always null

### ISSUE THREAD

**Issue by sameh-khemira** [blackhorse-one/stomp_dart_client#12]
Hello, 
After installing the package I notice that the callback in stomp.dart is marked in red and showing an error
![Capture du 2020-04-02 08-07-34](https://user-images.githubusercontent.com/63003798/78220880-40e96c80-74ba-11ea-9d02-49991ac0f2a3.png).
And after testing my callback function is always  null
![Capture du 2020-04-02 08-33-07](https://user-images.githubusercontent.com/63003798/78242759-8027b580-74da-11ea-8633-a733a0c28bf3.png)
And here is the part of the code where I am using the stomp
![Capture du 2020-04-02 08-08-08](https://user-images.githubusercontent.com/63003798/78243550-e3feae00-74db-11ea-8239-2a80e52be7ba.png)

**Comment by KammererTob** [comment]
Hi,

the first image looks like a linting problem. Can you let me know what version of Dart and Dart Code (assuming you use this extension) you are using?
And do you maybe have your code in writing for me to be able to check it out? I cannot really replicate the problems you are having.

**Comment by KammererTob** [comment]
I will close this issue. If you still have problems feel free to reopen it.
