### ISSUE TITLE
Uncaught Exception on .activate()

### ISSUE THREAD

**Issue by lfdominguez** [blackhorse-one/stomp_dart_client#17]
Hi, I'm first using your lib and I get from debugger an Uncaught Exception when I execute .activate() function and the WebSocket Server is down, even surround between try catch block. Even I was defined a function for `onWebSocketError` but is not executed, i think that because the exception throw before websocket connect.

![image](https://user-images.githubusercontent.com/5604131/81490679-10cc8080-9253-11ea-9142-3571d2af42b8.png)
![image](https://user-images.githubusercontent.com/5604131/81490685-1e820600-9253-11ea-9159-3f6c4a0fd442.png)
![image](https://user-images.githubusercontent.com/5604131/81490693-3d809800-9253-11ea-8320-f020c61083a9.png)

I think that the problem is that .activate() call an async function that execute outside try catch block...???

**Comment by KammererTob** [comment]
Hey, thanks for the issue.
Fixed with https://github.com/blackhorse-one/stomp_dart_client/commit/aa1ab761cdfe1fb6b0185f773563fb6b94a86543.
Released with 0.3.3.

Please let me know if there are any problems with this approach
