### ISSUE TITLE
Handling connection error stomp 0.3.3 flutter/dart

### ISSUE THREAD

**Issue by teddynyambe** [blackhorse-one/stomp_dart_client#21]
When I put a wrong url/ip to my stomp spring service I don't get onWebSocketError fired up and does not print out error as in the code below:

`final stompClient = StompClient( config: StompConfig( url: 'ws://localhostxx:8080', onConnect: onConnect, onWebSocketError: (dynamic error) => print(error.toString()), stompConnectHeaders: {'Authorization': 'Bearer yourToken'}, webSocketConnectHeaders: {'Authorization': 'Bearer yourToken'}));`

I want to show a message to user that the connection is not available. But when I correct my ip accessing the socket without any problem. What am I missing here?

**Comment by KammererTob** [comment]
Hey,

thanks for the ticket.  I will check on this in the next few days

**Comment by teddynyambe** [comment]
OK great we wait to hear from you.

Kind regards,

Teddy L.

**Comment by KammererTob** [comment]
I habe just published a new version which should fix this on the VM/IO side at least. Sadly i did not find a way to do the same on the HTML side (probably connected to this: https://github.com/dart-lang/web_socket_channel/issues/38). I will close this issue for now and wrote me down a note to have a look at HTML again in the future.
