### ISSUE TITLE
onDebugMessage doesn't work

### ISSUE THREAD

**Issue by guillaume-fortin-keyneosoft** [blackhorse-one/stomp_dart_client#22]
Can you add onDebugMessage inside StompConfig copyWith method?

when StompConfig copyWith  method is called, the onDebugMessage calback is copied with _noOp default value.

So i can't debug websocket messages.

**Comment by KammererTob** [comment]
Hey. 

Thanks for reporting this issue. I have just published a new version which should have this fixed.
