### ISSUE TITLE
return a future for every message sending

### ISSUE THREAD

**Issue by RonnieRen** [blackhorse-one/stomp_dart_client#27]
could you pls return a future or provide a way to get the progress of a message sending include sending error ?

**Comment by KammererTob** [comment]
Hey.

This library uses [WebSocketChannel](https://github.com/dart-lang/web_socket_channel) for the communication via WebSockets. There is no way to get information on the progress of the message sent and if it was received by the server. You could use ack/nack (if the server supports those) to receive a message when the server accepted the message.
