### ISSUE TITLE
Could not connect websocket on SpringBoot + SockJS

### ISSUE THREAD

**Issue by bambinoua** [blackhorse-one/stomp_dart_client#34]
I am implementing you package in web app. The code example below. When I click on button I expect an least the connection to remote server (Networks tab of browser inspector) but I didn't see it. Object is created. Then I call `activate` method bu `onConnect` callback does not call. Does the pacakge really works under web environment? What I did wrong? Please help.
```dart
onPressed: () {
  final client = StompClient(
    config: StompConfig.SockJs(
      url: 'http://10.1.1.1:8080/topics',
      onConnect: (cli, frm) {
        print('connected'); // never printed
      }
    ),
  );
  client.activate();
}
```

**Comment by Petrol-** [comment]
your URL should be targeting a WebSocket:
instead of `http://10.1.1.1:8080/topics`
it should be : `ws://10.1.1.1:8080/topics`

**Comment by bambinoua** [comment]
I use example from this [page](https://pub.dev/packages/stomp_dart_client/example) just in regular `main.dart` which I run with `dart main.dart` and where I use url with `http` and example is working. Why the same example does not work under web? Is it some limitation? Is it described somewhere?

**Comment by Petrol-** [comment]
Well I don't know then. I've started using this lib only a week ago or so but  I'am able to connect with flutter web.

Maybe you can put a breakpoint inside [StompHandler.start()](https://github.com/blackhorse-one/stomp_dart_client/blob/master/lib/stomp_handler.dart).  I'm pretty sure you'll find more infos about your issue (I had problems to connect and this helped me a lot figuring out the issue)

**Comment by bambinoua** [comment]
I set a break point and I see the DomException because I cannot use `http` and must use `wss` or `ws`. But I use StompConfig.useSockJs(). And some example:
```javascript
<script>
	    var ws = new SockJS("http://localhost:8080/init");
	    ws.onmessage = function(data){  console.log(data);  }
	</script>
```
Maybe you have a bug?

**Comment by bambinoua** [comment]
@Petrol- what server do you use? we are using Spring boot + SockJs

**Comment by Petrol-** [comment]
Oh, there is a bug with SockJS and flutter Web (#32) The fix has been merged on master but is not yet on pub.dev
 
I'm also using Spring Boot
```
    @Override
    public void configureMessageBroker(MessageBrokerRegistry config) {
        config.enableSimpleBroker("/review");
        config.setApplicationDestinationPrefixes("/app");
    }

    @Override
    public void registerStompEndpoints(StompEndpointRegistry registry) {
        registry.addEndpoint("/rev")
                .setAllowedOrigins("*")
                .withSockJS();
    }
```

And I can connect using 
```
 _client = StompClient(
        config: StompConfig.SockJS(
      url: "http://localhost:8080/rev",
      onConnect: _onConnect,
    ));
```

**Comment by bambinoua** [comment]
@Petrol- but you have the problem with `#`. I have something like this one:

> DomException (SyntaxError: Failed to construct 'WebSocket': ws or wss are alowed. You cannot use `http`).

But maybe they are lrelated

**Comment by Petrol-** [comment]
Well this is strange because if you re using StompConfig.SockJS()  it should automatically convert the url (http://yourUrl) to websocket (ws://yoururl/...) or throw an exception.

Do you have an small example project that shows the problem ?

**Comment by bambinoua** [comment]
@Petrol- it seems the problem is gone when I import from master git. I think it was related to bug you noticed and they fixed. But now I have a problem with authorization header. I think 2 kinds of connect method under `dart wm` and `web`:

_connect_io.dart
```dart
var websocket = WebSocket.connect(config.url. headers: config.webSocketConnectHeaders);
```

_connect_html.dart
```dart
var websocket = WebSocket(config.url)..binaryType = BinaryType.list.value;
```
In html implementation there is no possibility to send authorization headers (or even any headers).

**Comment by bambinoua** [comment]
It seems after import package from git master the problem is gone.
