### ISSUE TITLE
Cannot sent HTTP headers using flutter web

### ISSUE THREAD

**Issue by bambinoua** [blackhorse-one/stomp_dart_client#35]
I have a problem with sending authorization header because I need secure connection to websocket. I see two kinds of connect method under `dart wm` and `web`:

_connect_io.dart
```dart
Future<WebSocketChannel> connect(StompConfig config) async {
  var websocket = WebSocket.connect(config.url. headers: config.webSocketConnectHeaders); // headers are passed
  ...
}
```

_connect_html.dart
```dart
Future<WebSocketChannel> connect(StompConfig config) async {
  var websocket = WebSocket(config.url)..binaryType = BinaryType.list.value; // where the headers?
  ...
}
```
In html implementation there is no possibility to send authorization headers (or even any headers). Is it possible to fix this? Do you know some workaround for a while?

**Comment by Rouvo** [comment]
Hi there,
after struggling with the already fixed hash bug i came across this aswell. 
I also have to send a body, which is fine when using it in STOMP.js via 
`(void) send(destination, headers = {}, body = '')`

I need the option to send headers and a body

**Comment by KammererTob** [comment]
The WebSocket API in JS does provide a way to declare headers: https://html.spec.whatwg.org/multipage/web-sockets.html#network

Your best bet for authorization (this is how i am doing it at least) is probably to send the authorization header with your STOMP connect message. This should work between different platforms.
