### ISSUE TITLE
Unable to connect SockJS when using https

### ISSUE THREAD

**Issue by tranduc3sao** [blackhorse-one/stomp_dart_client#36]
I try to connect SockJS to an http connection and the connection is successful. Do not know if this is a bug or the library is not supported

`stomp_dart_client: ^0.3.7`

```
[✓] Flutter (Channel unknown, v1.17.5, on Mac OS X 10.15.7 19H2, locale vi-VN)
    • Flutter version 1.17.5 at /Users/tranduc/Documents/install/flutter
    • Framework revision 8af6b2f038 (4 months ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tranduc/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • iPhone 12 Pro Max • 515E44A7-03EF-429D-B020-C8CA494B3815 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-1 (simulator)

! Doctor found issues in 1 category.
Process finished with exit code 0
```

**Comment by KammererTob** [comment]
Thanks for the report. I will have a look in the next few days.

**Comment by KammererTob** [comment]
Hey. I was able to connect to https just fine. My test client:

```
final stompClient = StompClient(
    config: StompConfig.SockJS(
        url: 'https://127.0.0.1:9999/sockjs',
        onConnect: onConnect,
        onWebSocketError: (dynamic error) => print(error.toString()),
        onDebugMessage: (dynamic msg) => print(msg.toString()),
        reconnectDelay: 0,
        connectionTimeout: Duration(seconds: 2)
    )
);
```

Can you maybe share some code or error message?

**Comment by tranduc3sao** [comment]
> Hey. I was able to connect to https just fine. My test client:
> 
> ```
> final stompClient = StompClient(
>     config: StompConfig.SockJS(
>         url: 'https://127.0.0.1:9999/sockjs',
>         onConnect: onConnect,
>         onWebSocketError: (dynamic error) => print(error.toString()),
>         onDebugMessage: (dynamic msg) => print(msg.toString()),
>         reconnectDelay: 0,
>         connectionTimeout: Duration(seconds: 2)
>     )
> );
> ```
> 
> Can you maybe share some code or error message?

It has no error messages. I think the problem is in the header. You can try with a header connection

```
client = StompClient(
      config: StompConfig.SockJS(
        url: _server,
        stompConnectHeaders: {"username": "tranduc"},
        onConnect: (StompClient client, StompFrame connectFrame) {
          print('Connect success');
          _loadOnline(true);
          client.subscribe(
            destination: _message,
            headers: _headerConnect,
            callback: (StompFrame frame) {
              String message = frame.body;
              _loadMessage(message);
            },
          );
        },
        onWebSocketDone: () {
          print('onWebSocketDone');
          _loadOnline(false);
        },
      ),
    );
```

**Comment by tranduc3sao** [comment]
I debug out an error message 

`Connection to 'https://myhost/chat/315/zrgw2erk/websocket#' was not upgraded to websocket`

I have two identical http and https servers. The normal http connection. Do not know what I'm having problems

**Comment by KammererTob** [comment]
Are you using this library in a web environment? If yes, then could you please try to point your pubspec.yaml to the latest master.
If no: Are you certificates self signed? The error message sounds a bit like it is a normal websocket server which does not support SockJS, but i am not very expierenced when it comes to SockJS.

**Comment by KammererTob** [comment]
I am going to close this issue due to inactivity. If you still have problems please reopen it.

**Comment by LiangHuangBC** [comment]
Self signed cert is not support. I have the same issue.
