### ISSUE TITLE
Send message to a specific user

### ISSUE THREAD

**Issue by davsantos13** [blackhorse-one/stomp_dart_client#39]
Hello, 

I would like know, if with this package, I can send messages to a specific user.

In JavaScript I've see something like this : 

function connect() {
    var socket = new SockJS('/connect');
    stompClient = Stomp.over(socket);
    stompClient.connect({
           "user" : user Here
    } , function (frame) {
        stompClient.subscribe('/user/queue/reply', function(greeting) { greeting.body  });
    });
}

**Comment by KammererTob** [comment]
I am not sure i understand correctly, but with stomp it is possible to listen/send only specific messages. Here is Spring as an example:

https://docs.spring.io/spring-framework/docs/current/reference/html/web.html#websocket-stomp-user-destination
