### ISSUE TITLE
singleton for the StompClient

### ISSUE THREAD

**Issue by huhx** [blackhorse-one/stomp_dart_client#4]
In some cases, I do not want to close the connection when I leave the page. But when I enter this screen again. Always create new StompClient for me, and the previous StompClient is still connected.

I wandering that if it can be a singleton, and if it can support the subscribe management.

**Comment by KammererTob** [comment]
Hey,

i don't think that this is an issue with the lib. You can just wrap the client yourself and make the wrapper a Singleton. Like this:

```
class StompService {
  StompClient _stompClient;

  StompClient get client => _stompClient;

  static final StompService instance = StompService._privateConstructor();
  StompService._privateConstructor() {
    _stompClient = StompClient(
      config: StompConfig(
        url: config.stompUrl,
        connectionTimeout: Duration(milliseconds: 3000),
        stompConnectHeaders: {},
        beforeConnect: _beforeConnect,
        onConnect: _onConnect,
        onDisconnect: _onDisconnect,
        onWebSocketDone: _onWebSocketDone
      )
    );
  }
```

And then use it like this:

```
StompService.instance.client.activate()
StompService.instance.client.subscribe(...)
```

Hope this helps. I am closing the issue, but if you still feel that this should be part of the library feel free to open it again.

**Comment by huhx** [comment]
thank you.
