### ISSUE TITLE
After successful connection of StompConfig, the disconnect instruction is sent.

### ISSUE THREAD

**Issue by zc1003** [blackhorse-one/stomp_dart_client#41]
When I use this package to connect to websocket successfully, the callback of successful connection is not triggered. However, the server receives a connection instruction and a disconnection instruction. My code is like this
```
final StompClient client = StompClient(
      config: StompConfig(
          url: 'ws://192.168.0.120:8091/',
          reconnectDelay: 0,
          onConnect: (StompClient client, StompFrame connectFrame) {
            print("onConnect");
          },
          stompConnectHeaders: {},
          onWebSocketError: (dynamic error) => print(error.toString()),
          onDisconnect: (StompFrame frame) => { print("onDisconnect") },
          onStompError: (StompFrame frame) => { print("onStompError") },
          onDebugMessage: (String frame) => { print(frame) },
          onUnhandledFrame: (StompFrame frame) => { print("onUnhandledFrame") },
          onUnhandledMessage: (StompFrame frame) => { print("onUnhandledMessage") },
          onWebSocketDone: () => {print("onWebSocketDone")}
          ));

void main() {
  client.activate();
}
```

**Comment by KammererTob** [comment]
Have you checked the status code/reason for the disconnect instruction on the server?

If this is your complete code i guess that the client is garbage collected before it can even trigger the connection callback.

**Comment by zc1003** [comment]
Thank you for your answer sincerely.
The above code is complete, and the client is not garbage collected.
The server disconnected because it received the disconnection instruction from the client, but I didn't execute the disconnection instruction. And I received some printed messages as follows
```
>>> CONNECT
accept-version:1.0,1.1,1.2
heart-beat:5000,5000

onWebSocketDone
```

**Comment by zc1003** [comment]
In the source code of the project, I noticed that the client's judgment of whether the connection is successful depends on the server's response field ‘command’ content equals "CONNECT" or not.

This is not consistent with the description in stomp protocol specification. The specification requires that the server reponses returned 'CONNECTD' and not 'CONNECT' command when connection sucessful.

**Comment by KammererTob** [comment]
Hey,

where are you seeing this in the source. This is the snippet which handles the responses from the server:
```
void _onFrame(StompFrame frame) {
    switch (frame.command) {
      case 'CONNECTED':
        _onConnectFrame(frame);
        break;
      case 'MESSAGE':
        _onMessageFrame(frame);
        break;
      case 'RECEIPT':
        _onReceiptFrame(frame);
        break;
      case 'ERROR':
        _onErrorFrame(frame);
        break;
      default:
        _onUnhandledFrame(frame);
    }
  }
```

As you can see it reacts to the 'CONNECTED' command from the server.

**Comment by KammererTob** [comment]
I'll close this issue for now. If you still have issues please feel free to reopen it.
