### ISSUE TITLE
HeartBeat Duration

### ISSUE THREAD

**Issue by inZaCz** [blackhorse-one/stomp_dart_client#45]
I am trying to use this library to connect to websocket servers. During the handshaking client sending this connect _CONNECT
accept-version:1.0,1.1,1.2
heart-beat:0:00:00.000000,0:00:00.000000_
(this is message for heartbeat set to empty Duration(), for any time value it does not work too)
the format of hear beat is wrong and every WS with stomp returns ERROR message.

If I edit the lib and put in connectHeaders  plain numbers it just work. Probably issue with Duration output format..

**Comment by KammererTob** [comment]
Hey. Thanks for the report. I've pushed a fix and prepared a new version 0.4.1 which should fix this issue. Please let me know if it doesn't.
