### ISSUE TITLE
Problems connecting from browser - working in test environment

### ISSUE THREAD

**Issue by TKalo** [blackhorse-one/stomp_dart_client#47]
```dart    
class MVCWS{
  String value1 = 'value';
  String value2 = 'value';
  StompClient client;
  Future<bool> login() async {
    Completer<bool> completer = new Completer();
    client = StompClient(
      config: StompConfig(
          url: 'ws://localhost:8080/schedule-application-websocket',
          onConnect: (StompFrame frame){
            print('connected');
            completer.complete(true);
          },
          beforeConnect: () async {
            print('connecting...');
          },
          onWebSocketError: (dynamic error) => (){
            client = null;
            completer.complete(false);
          },
          webSocketConnectHeaders: {'value1': value1,'value2':PasswordEncoder.encode(value2)},
          connectionTimeout: Duration(seconds: 10)
      ),
    );
    client.activate();

    return completer.future;
  }
}
```

I have set up a spring WebSocket server to handle this request.
The above code works when using it in a test.
When I use it in a browser application, the server receives no connection.
I have placed print methods in the servers handshake method, and they don't show for the application.

Looking past this hurdle the rest of the package is great and exactly what I need for my project, thank you for that!

**Comment by KammererTob** [comment]
Hey,

what version are you using? Have you tried to print out any errors in the onWebSocketError and onStompError callback?

**Comment by TKalo** [comment]
I'm using 0.4.1, I assume that's the latest. 

I do react to WebSocket errors but didn't print out stomp errors. The connection newer reaches the handshake so I assume it cannot be a stomp error. I have tried it now but nothing is printed. It simply reconnects.

**Comment by KammererTob** [comment]
I've tried the example code in the repository with my local Spring server with `flutter run -d chrome example/main.dart` and that worked fine. 

```
final stompClient = StompClient(
  config: StompConfig(
    url: 'ws://localhost:8080/display',
    onConnect: (_) {
      print('connected');
    },
    beforeConnect: () async {
      print('waiting to connect...');
      await Future.delayed(Duration(milliseconds: 200));
      print('connecting...');
    },
    onWebSocketError: (dynamic error) => print(error.toString()),
  ),
);

void main() {
  stompClient.activate();
}
```

What status code is the Network tab in chrome giving you for the websocket request?

**Comment by TKalo** [comment]
403.
I'm new to WebSockets, and so I'm not completely sure how the connection procedure goes. I figured the first step would be the handshake, and so any errors I could detect in the WebSocket server handshake, but as stated, the connection never comes that far. Do you know what parts of the connection process could intercept the handshake, which would only affect a browser connection?

**Comment by KammererTob** [comment]
403 means Forbidden. You probably need to allow your localhost/domain as origin, or just allow all origins. This is done in the registry where you add your endpoint to Spring. This is also something which only affects the browser, so it would make sense here.

`registry.addEndpoint("/messaging").setAllowedOrigins("*");`

**Comment by TKalo** [comment]
That was a simpler issue than I expected, sorry bout that. I figured dart and chrome would fire from ports of equal status. Thank you
