### ISSUE TITLE
Need help! Springboot websocket + flutter - not receiving messages from backend

### ISSUE THREAD

**Issue by boozywoozy** [blackhorse-one/stomp_dart_client#49]
Hello, i'm use flutter as frontend and springboot as backend.
For now my app can connect to backend via websocket, can subscribe for channel, can send message from frontend to backend,
but flutter app didn't recieve any messages from backend and i get no errors.

Flutter part:
```_connectSocket() {
  Map<String, String> _headers=Map();
  _headers.addAll({'authorization':'${globals.tokenType} ${globals.token}'});
  
  if (_socketServer.isNotEmpty) {
    //_socketServer=_socketServer.replaceFirst(new RegExp(r'https://'), 'wss://');
    _socketServer+='ws';
  }
  
  client = StompClient(
      config: StompConfig.SockJS(
          url: _socketServer,
          //connectionTimeout: Duration(seconds: 8),
          onConnect: _socketOnConnect,
          stompConnectHeaders: _headers,
          onDebugMessage: (frame) {
            print('WebSocket - onDebugMessage executed! - $frame');
          },
          onStompError: (StompFrame frame) {
              print('A stomp error occurred in web socket connection :: ${frame.toString()}');
          },
          onWebSocketError: (dynamic frame) {
              print('A Web socket error occurred in web socket connection :: ${frame.toString()}');
          },
          onWebSocketDone: () {
              print('WebSocket - onWebSocketDone executed!');
          },
          onDisconnect: (frame) {
            print('WebSocket - onDisconnect executed! ${frame.toString()}');
          },
          onUnhandledFrame: (frame) {
            print('WebSocket - onUnhandledFrame executed! ${frame.toString()}');
          },
          onUnhandledMessage: (frame) {
            print('WebSocket - onUnhandledMessage executed! ${frame.toString()}');
          },
          onUnhandledReceipt: (frame) {
            print('WebSocket - onUnhandledReceipt executed! ${frame.toString()}');
          },
      )
  );
  print('try to connect wss to: $_socketServer');
    try {
      client.activate();
      print('[1] Socket client activated.');
      if (mounted) {
        setState(() {
          _isSocketConnected=true;
        });
      }
    } catch(e) {
      print('!!!===Socket connection error: $e');
      client?.deactivate();
    }
  }

  _socketOnConnect(StompFrame data) {
    print('On connect: ${client.config.url.toString()} | ${data.body} | ${data.headers}');
    unsub=client.subscribe(destination: '/websocket/app',
          callback: _socketIncomingMessage
    );
    client.send(destination: '/websocket/send', body: 'SOCKET TEST');
  }
  
  _socketIncomingMessage(StompFrame data) {
    print('Received message from subscribed channel: ${data.toString()}');
  }

  _disconnectSocket() {
    try {
      unsub();
      client?.deactivate();
      print('[2] Socket client is deactivated.');
      unsub=null;
      if (mounted) {
        setState(() {
          _isSocketConnected=false;
        });
      }
    }
    catch(e) {
      print('!!!===Socket disconnection error: $e');
      unsub=null;
    }
  }
```
flutter debug output:

> I/flutter ( 3826): WebSocket - onDebugMessage executed! - >>> ["CONNECT\nauthorization:Bearer ************************************************* \naccept-version:1.0,1.1,1.2\nheart-beat:5000,5000\n\n\u0000"]
I/flutter ( 3826): WebSocket - onDebugMessage executed! - <<< o
I/flutter ( 3826): WebSocket - onDebugMessage executed! - <<< a["CONNECTED\nversion:1.2\nheart-beat:0,0\nuser-name:************************* \n\n\u0000"]
I/flutter ( 3826): On connect: wss://***.***.*.*:8443/websocket/082/ppqcum2j/websocket |  | {version: 1.2, heart-beat: 0,0, user-name: *****************}
I/flutter ( 3826): WebSocket - onDebugMessage executed! - >>> ["SUBSCRIBE\ndestination:/websocket/app\nid:sub-0\n\n\u0000"]
I/flutter ( 3826): WebSocket - onDebugMessage executed! - >>> ["SEND\ndestination:/websocket/send\ncontent-length:11\n\nSOCKET TEST\u0000"]
I/flutter ( 3826): WebSocket - onDebugMessage executed! - <<< h
I/flutter ( 3826): WebSocket - onDebugMessage executed! - <<< h
I/flutter ( 3826): WebSocket - onDebugMessage executed! - <<< h
I/flutter ( 3826): WebSocket - onDebugMessage executed! - <<< h
I/flutter ( 3826): WebSocket - onDebugMessage executed! - <<< h
I/flutter ( 3826): WebSocket - onDebugMessage executed! - <<< h

Spring boot message controller and debug output:
```@Slf4j
@RestController
public class MessageController {
    @Autowired
    private SimpMessageSendingOperations messagingTemplate;

    @MessageMapping("/send")
    public void onReceiveMessage(@Payload String chatMessage, @CurrentUser UserPrincipal userPrincipal) {
        System.out.println("Received message from client - [userName:"+userPrincipal.getUsername()+
            "] - [userEmail:"+userPrincipal.getEmail()+"] - [userId:"+userPrincipal.getId()+"] - message: "+
            chatMessage);
        messagingTemplate.convertAndSend("/websocket/app", chatMessage);
    }
}
```

>14:27:10.941 [https-openssl-nio-8443-exec-8] DEBUG o.s.web.filter.CommonsRequestLoggingFilter - Before request [GET /websocket/082/ppqcum2j/websocket, client=***.***.*.** , headers=[user-agent:"Dart/2.12 (dart:io)", connection:"Upgrade", cache-control:"no-cache", accept-encoding:"gzip", content-length:"0", sec-websocket-version:"13", host:"***.**.*.*:8443", sec-websocket-extensions:"permessage-deflate; client_max_window_bits", sec-websocket-key:"*************", upgrade:"websocket"]]

>Stomp command CONNECT received!

>Received a new websocket connection. - SessionConnectedEvent[GenericMessage [payload=byte[0], headers={simpMessageType=CONNECT_ACK, simpConnectMessage=GenericMessage [payload=byte[0], headers={simpMessageType=CONNECT, stompCommand=CONNECT, nativeHeaders={authorization=[Bearer ************************************************************************************************************************], accept-version=[1.0,1.1,1.2], heart-beat=[5000,5000]}, simpSessionAttributes={}, simpHeartbeat=[J@476bdeff, simpUser=org.springframework.security.authentication.UsernamePasswordAuthenticationToken@db12a52: Principal: *******************************.security.UserPrincipal@49ac2862; Credentials: [PROTECTED]; Authenticated: true; Details: null; Granted Authorities: ROLE_USER, simpSessionId=ppqcum2j}], Stomp command SUBSCRIBE received!

>Subscribe user is: ********************

>Received a subscribe event from websocket. - SessionSubscribeEvent[GenericMessage [payload=byte[0], headers={simpMessageType=SUBSCRIBE, stompCommand=SUBSCRIBE, nativeHeaders={destination=[/websocket/app], id=[sub-0]}, simpSessionAttributes={}, simpHeartbeat=[J@4219c8bd, simpSubscriptionId=sub-0, simpUser=org.springframework.security.authentication.UsernamePasswordAuthenticationToken@db12a52: Principal: *********************************.security.UserPrincipal@49ac2862; Credentials: [PROTECTED]; Authenticated: true; Details: null; Granted Authorities: ROLE_USER, simpSessionId=ppqcum2j, simpDestination=/websocket/app}]]

>Reply channel is: /websocket/app | id=sub-0

>Received message from client - [userName:********************* ] - [ userId: ************************* ] - message: SOCKET TEST

**Comment by KammererTob** [comment]
Hey,

how does your WebSocketConfig in Spring Boot look like? Specifcally the destrinationPrefixes of your Broker.

**Comment by boozywoozy** [comment]
WebSocketConfiguration:

```@Configuration
@EnableWebSocketMessageBroker
@Order(Ordered.HIGHEST_PRECEDENCE+99)
public class WebSocketConfiguration implements WebSocketMessageBrokerConfigurer {

  @Autowired
  private AppProperties appProperties;

  @Override
  public void configureMessageBroker(MessageBrokerRegistry config) {
    Lists.newArrayList(appProperties.getWebSocket().getDestinations()).forEach(
        (x)->System.out.println("Stomp destination: "+x));
    Lists.newArrayList(appProperties.getWebSocket().getPrefixes()).forEach(
        (x)->System.out.println("Stomp prefix: "+x));
    System.out.println();
    config
        .enableSimpleBroker(appProperties.getWebSocket().getDestinations());
    config
        .setApplicationDestinationPrefixes(appProperties.getWebSocket().getPrefixes());
  }

  @Override
  public void registerStompEndpoints(StompEndpointRegistry registry) {
    registry
        .addEndpoint(appProperties.getWebSocket().getSocketEndpoints())
        .setAllowedOrigins("*")
        .withSockJS();
  }

    @Override
    public void configureClientInboundChannel(ChannelRegistration registration) {
        registration.interceptors(tokenWebSocketInterceptor());
    }

    @Bean
    public TokenWebSocketInterceptor tokenWebSocketInterceptor() {
        return new TokenWebSocketInterceptor();
    }
}
```

application.properties:

```
app.webSocket.socketEndpoints=/ws
app.webSocket.prefixes=/websocket
app.webSocket.destinations=/app, /chat, /admin
```

**Comment by KammererTob** [comment]
Hey. 

Can you try to subscribe to "/chat/app" and also send the message to "/chat/app" instead?

**Comment by boozywoozy** [comment]
It doesn't work - i can subscribe and i can send message to this channel from client side, but i even not get this message on backend side. And i think it's impossible coz in my project configured prefix is "/websocket".

**Comment by boozywoozy** [comment]
Ok, i found the problem.
It works if remove .withSockJS(); from websocket configuration in spring boot.
Thank you for answers.

**Comment by KammererTob** [comment]
Glad you found the problem!

**Comment by boozywoozy** [comment]
Sorry, been away for awhile. I was wrong - still not receive messages from server.
I think this message in console was an echo message from server:

> I/flutter ( 7169): WebSocket - onDebugMessage executed! - >>> SEND
> I/flutter ( 7169): destination:/socket/app/test
> I/flutter ( 7169): content-length:11
> I/flutter ( 7169):
> I/flutter ( 7169): SOCKET TEST

But this is just a debug massage from your plugin.

**Comment by boozywoozy** [comment]
Found post with same problem on Stackoverflow:
https://stackoverflow.com/questions/66226055/flutter-websocket-using-stomp-message-not-receiving

**Comment by KammererTob** [comment]
Hey. I think you got your prefixes confused.

`config.setApplicationDestinationPrefixes(appProperties.getWebSocket().getPrefixes());` this prefix is used for incoming messages so that only those with the specified prefix are routed correctly to your controller. In your client you send a message to `/websocket/send` while your method is annoted with `@MessageMapping("/send")` which is correct and as you noted this already works. The prefix in your config is `/websocket`

Now `config.enableSimpleBroker(appProperties.getWebSocket().getDestinations());`. The destination prefixes passed here are used for the broker to know which messages are actually meant for the broker to process. The prefixes you have defined are `/app, /chat, /admin`. This means, that your client would need to subscribe to `/app/messages`, and your server would also need to `convertAndSend` to `/app/messages`

If this does not work, i would suggest using the default prefixes, which normally are:
`messageBrokerRegistry.setApplicationDestinationPrefixes("/app");` - so messages sent from the client to server need to be prefixed by `/app`
and
`messageBrokerRegistry.enableSimpleBroker("/topic", "/queue")` - so subscriptions (and messages for a subscription) need to be prefixed with `/topic`. `/queue` is used for subscriptions/messages for a specific user.

**Comment by boozywoozy** [comment]
Hi, thank you for answer.
So i change a little bit my code for test:

**Spring boot:**

```
@Configuration
@EnableWebSocketMessageBroker
@Order(Ordered.HIGHEST_PRECEDENCE+99)
public class WebSocketConfiguration implements WebSocketMessageBrokerConfigurer {

  @Autowired
  private AppProperties appProperties;

  @Override
  public void configureMessageBroker(MessageBrokerRegistry config) {
    config
        //.enableSimpleBroker(appProperties.getWebSocket().getDestinations())
        .enableSimpleBroker("/app")
        .setTaskScheduler(new DefaultManagedTaskScheduler())
        .setHeartbeatValue(new long[]{0,35000});
    config
        //.setApplicationDestinationPrefixes(appProperties.getWebSocket().getPrefixes());
        .setApplicationDestinationPrefixes("/test");
  }

  @Override
  public void registerStompEndpoints(StompEndpointRegistry registry) {
    registry
        //.addEndpoint(appProperties.getWebSocket().getSocketEndpoints())
        .addEndpoint("/ws")
        //.setHandshakeHandler(new SocketHandler())
        //.addInterceptors(tokenWebSocketInterceptor())
        .setAllowedOrigins("*");
        //.withSockJS();
  }

    @Override
    public void configureClientInboundChannel(ChannelRegistration registration) {
        registration.interceptors(tokenWebSocketInterceptor());
    }

    @Bean
    public TokenWebSocketInterceptor tokenWebSocketInterceptor() {
        return new TokenWebSocketInterceptor();
    }
}
```
```
@Controller
public class MessageController {

    @Autowired
    private SimpMessageSendingOperations messagingTemplate;

    @MessageMapping("/send")
    @SendTo("/app/test")
    public String onReceiveMessage(@Payload String chatMessage, @CurrentUser UserPrincipal userPrincipal) {
        System.out.println("Received message from client - [userName:"+userPrincipal.getUsername()+
            "] - [userEmail:"+userPrincipal.getEmail()+"] - [userId:"+userPrincipal.getId()+"] - message: "+
            chatMessage);
        return "From Server: "+chatMessage;
    }
}
```

**Flutter code:**
```
_socketOnConnect(StompFrame data) {
    print('On connect: ${client.config.url.toString()} | ${data.body} | ${data.headers}');
    unsub=client.subscribe(destination: '/app/test',
          callback: 
                  (frame) {
                    print('Received message from subscribed channel: $frame');
                  }
    );
    client.send(destination: '/app/send', body: 'SOCKET TEST');
  }
```

**Flutter debug output:**

> I/flutter (26937): try to connect wss to: wss://192.168.1.9:8443/ws
> I/flutter (26937): [1] Socket client activated.
> I/flutter (26937): WebSocket - onDebugMessage executed! - >>> CONNECT
> I/flutter (26937): authorization: **************************************************************************************
> I/flutter (26937): accept-version:1.0,1.1,1.2
> I/flutter (26937):
> I/flutter (26937): WebSocket - onDebugMessage executed! - <<< CONNECTED
> I/flutter (26937): version:1.2
> I/flutter (26937): heart-beat:0,35000
> I/flutter (26937): user-name: *************
> I/flutter (26937):
> I/flutter (26937): On connect: wss://192.168.1.9:8443/ws |  | {version: 1.2, heart-beat: 0,35000, user-name: *************** }
> I/flutter (26937): WebSocket - onDebugMessage executed! - >>> SUBSCRIBE
> I/flutter (26937): destination:/app/test
> I/flutter (26937): id:sub-0
> I/flutter (26937):
> I/flutter (26937): WebSocket - onDebugMessage executed! - >>> SEND
> I/flutter (26937): destination:/app/send
> I/flutter (26937): content-length:11
> I/flutter (26937):
> I/flutter (26937): SOCKET TEST
> I/flutter (26937): WebSocket - onDebugMessage executed! - >>> PING
> I/flutter (26937): WebSocket - onDebugMessage executed! - >>> UNSUBSCRIBE
> I/flutter (26937): id:sub-0
> I/flutter (26937):
> I/flutter (26937): [2] Socket client is deactivated.
> I/flutter (26937): WebSocket - onDebugMessage executed! - >>> DISCONNECT
> I/flutter (26937): receipt:disconnect-0

**Spring boot debug output:**

> [https-openssl-nio-8443-exec-10] DEBUG o.s.web.filter.CommonsRequestLoggingFilter - Before request
> [GET /ws, client=192.168.1.30, headers=[user-agent:"Dart/2.12 (dart:io)", heart-beat:"[30000,30000]",
> connection:"Upgrade", cache-control:"no-cache", accept-encoding:"gzip", content-length:"0", sec-websocket-version:"13",
> host:"192.168.1.9:8443", authorization:"??????????????????????????????????????????????????????????????????????????",
> sec-websocket-extensions:"permessage-deflate; client_max_window_bits", sec-websocket-key:"???????????????????????",
> upgrade:"websocket"]]
> 
> Stomp command CONNECT received! [Channel:ExecutorSubscribableChannel[clientInboundChannel]]
> Received a new websocket connection. - SessionConnectedEvent[GenericMessage [payload=byte[0],
> headers={simpMessageType=CONNECT_ACK, simpConnectMessage=GenericMessage [payload=byte[0],
> headers={simpMessageType=CONNECT, stompCommand=CONNECT, nativeHeaders={authorization=[?????????????????????????????????],
> heart-beat=[25000,25000], accept-version=[1.0,1.1,1.2]}, simpSessionAttributes={},
> simpHeartbeat=[J@2a3bff5c, simpUser=org.springframework.security.authentication.UsernamePasswordAuthenticationToken@3b76bfb:
> Principal: ???????????????????????????????.UserPrincipal@47aa69cb;
> Credentials: [PROTECTED]; Authenticated: true; Details: null; Granted Authorities: ROLE_USER,
> simpSessionId=????????????????????????????????}]
> 
> Stomp command SUBSCRIBE received!
> Subscribe user is: ??????????????????????????
> Subscribe accessor.getDestination()=/app/test
> Subscribe successfull!
> 
> Received a subscribe event from websocket. -
> SessionSubscribeEvent[GenericMessage [payload=byte[0], headers={simpMessageType=SUBSCRIBE, stompCommand=SUBSCRIBE,
> nativeHeaders={destination=[/app/test], id=[sub-0]}, simpSessionAttributes={},
> simpHeartbeat=[J@46c41ca6, simpSubscriptionId=sub-0,
> simpUser=org.springframework.security.authentication.UsernamePasswordAuthenticationToken@3b76bfb:
> Principal: ?????????????????????????.UserPrincipal@47aa69cb; Credentials: [PROTECTED]; Authenticated: true;
> Details: null; Granted Authorities: ROLE_USER, simpSessionId=?????????????????????????, simpDestination=/app/test}]]
> 
> Received an unsubscribe event from websocket. -
> SessionUnsubscribeEvent[GenericMessage [payload=byte[0], headers={simpMessageType=UNSUBSCRIBE, stompCommand=UNSUBSCRIBE,
> nativeHeaders={id=[sub-0]}, simpSessionAttributes={}, simpHeartbeat=[J@2634d7a9,
> simpSubscriptionId=sub-0, simpUser=org.springframework.security.authentication.UsernamePasswordAuthenticationToken@3b76bfb:
> Principal: ????????????????????????.UserPrincipal@47aa69cb; Credentials: [PROTECTED]; Authenticated: true;
> Details: null; Granted Authorities: ROLE_USER, simpSessionId=????????????????????????????????????????????????????????????}]]
> 
> Disconnected from websocket. -
> SessionDisconnectEvent[sessionId=?????????????????????????????????, CloseStatus[code=1000, reason=null]]

So, as you see - result is the same.

**Comment by KammererTob** [comment]
Can you put a wait between subscribing and sending the message? I am also not seeing any log of the server receiving your send message. Are you sure that this is received?

**Comment by boozywoozy** [comment]
> Can you put a wait between subscribing and sending the message? I am also not seeing any log of the server receiving your send message. Are you sure that this is received?

Please see last part of my last answer.

**Comment by boozywoozy** [comment]
```
_socketOnConnect(StompFrame data) async {
    print('On connect: ${client.config.url.toString()} | ${data.body} | ${data.headers}');
    unsub=client.subscribe(destination: '/app/test',
          callback: 
                  (frame) {
                    print('Received message from subscribed channel: $frame');
                  }
    );
    await Future.delayed(Duration(seconds: 3));
    client.send(destination: '/app/send', body: 'SOCKET TEST', /*headers: _headers*/);
  }
```
Nothing changed.

**Comment by KammererTob** [comment]
Can you please try to use '/topic'  as your destinationPrefix inside `enableStompBroker` instead of `/test` and then only change the subscription destination in the flutter code to `/topic/test`, while also changing the `@SendTo` destination to `/topic/test`

**Comment by boozywoozy** [comment]
Ok, it's worked:

> I/flutter (10109): WebSocket - onDebugMessage executed! - >>> SEND
> I/flutter (10109): destination:/app/send
> I/flutter (10109): content-length:11
> I/flutter (10109):
> I/flutter (10109): SOCKET TEST
> I/flutter (10109): WebSocket - onDebugMessage executed! - <<< MESSAGE
> I/flutter (10109): destination:/topic/test
> I/flutter (10109): content-type:text/plain;charset=UTF-8
> I/flutter (10109): subscription:sub-0
> I/flutter (10109): message-id:63291be9-ae51-f84b-27f5-6f06031f4274-0
> I/flutter (10109): content-length:24
> I/flutter (10109):
> I/flutter (10109): From Server: SOCKET TEST
> I/flutter (10109): Received message from subscribed channel: Instance of 'StompFrame'
> I/flutter (10109): WebSocket - onDebugMessage executed! - >>> UNSUBSCRIBE
> I/flutter (10109): id:sub-0

So "/app" part is used only for sending message to server?
And one more question - can i subscribe direct to "/topic" without "/test" path?

**Comment by KammererTob** [comment]
Yes. `/app` is the prefix so that Spring knows to redirect the message to one of your handlers. I don't think that you directly subscribe to `/topic` because it is also just a prefix for the actual path after it. Although i am not 100% on that, especially since Spring looks a bit weird in this regards (for example, i am not sure why any other prefix as `/topic` would not work before)

**Comment by boozywoozy** [comment]
Thank you very much for help, be well, good luck.
