### ISSUE TITLE
Subscriptions persist after end of session

### ISSUE THREAD

**Issue by TKalo** [blackhorse-one/stomp_dart_client#50]
Hi again.

I'm using WebSocket to build a web app with live data.
When the app is destroyed, the WebSocket remains open.
I suppose I should call deactivate on the client when the app is destroyed.
There seems to be a conflict on this issue, calling a function when the app is destroyed.
I'm currently trying to call StompClient.deactivate() both with onDispose() and on didChangeAppLifecycleState.
neither works.

Is there something else I am supposed to use to clean up the WebSocket when the app is destroyed?

```dart
class _ApplicationState extends State<Application> with WidgetsBindingObserver{

  @override
  Widget build(BuildContext context) {

    return MaterialApp(...);
  }

  @override
    void didChangeAppLifecycleState(AppLifecycleState state) {
      print(state.toString());
      if(state == AppLifecycleState.inactive){
        log("INACTIVE");
        if(TempClientSingleton().client != null) TempClientSingleton().client.deactivate();
      }
      super.didChangeAppLifecycleState(state);
    }

  @mustCallSuper
  @protected
  @override
  void dispose() {
    if(TempClientSingleton().client != null) TempClientSingleton().client.deactivate();
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }
}
```

```dart
class TempClientSingleton{
  static final TempClientSingleton _singleton = TempClientSingleton._internal();
  factory TempClientSingleton(){return _singleton;}
  TempClientSingleton._internal();

  StompClient client;
}
```
```dart
class AuthenticationViewModel {
  static final AuthenticationViewModel _singleton = AuthenticationViewModel._internal();
  factory AuthenticationViewModel(){return _singleton;}
  AuthenticationViewModel._internal();

   ...

  void tryNewLogin() async {

      TempClientSingleton().client = WebSocketConnection().connect(
          email: loginEmail,
          password: loginPassword,
          userType: userType,
          onConnect: () async {},
          onError: (String error) {
            //Toast.show(error, context, duration: 3);
            MainViewModel().requestProgress.setData(RequestProgress.DENIED);
          }
      );
    }

  }
}
```

```dart
class WebSocketConnection{
  T cast<T>(x) => x is T ? x : null;

  StompClient connect({@required String email,@required String password,@required UserType userType,@required void Function() onConnect,@required void Function(String) onError}) {
    print('login attempt');
    if(email == null || password == null) return null;
    StompClient client = StompClient(
      config: StompConfig(
          url: 'ws://localhost:8080/schedule-application-websocket',
          reconnectDelay: Duration(milliseconds: 0),
          onConnect: (frame) => onConnect(),
          onWebSocketError: _onWebError,
          onStompError: _onStompError,
          webSocketConnectHeaders: {'email': email,'password':PasswordEncoder.encode(password), 'usertype' : EnumToString.convertToString(userType)},
          stompConnectHeaders: {'email': email,'password':PasswordEncoder.encode(password), 'usertype' : EnumToString.convertToString(userType)},
          connectionTimeout: Duration(seconds: 10)
      ),
    );

    client.activate();

    return client;
  }

  void _onStompError(StompFrame frame){
    //onError(frame.headers['message']);
  }

  void _onWebError(dynamic error){
    //onError(error);
  }
}

**Comment by KammererTob** [comment]
Hey,

i would have to check this for myself, but normally `deactivate` should shut down the connection and clean up. My first guess would be that somehow multiple clients are created, but only one is still accesible by your application. Can you share a bit more Code (specifically the Provider for the StompClientContainer)?

**Comment by TKalo** [comment]
I had actually changed the provider and am using a singleton instead. I have checked that "deactivate()" works as it should, it just isn't being called on app destroy. Therefore the WebSocket isn't being closed and subscriptions are still being triggered after the app is destroyed.

**Comment by KammererTob** [comment]
Replacing the client in the static Singleton will probably not immediatly destroy the client (since the GC will not run immediatly), so my guess is that somehow the client is overwritten with a new client, while the old one still is in memory for a while. I would probably (to narrow down the issue) call `TempClientSingleton().client?.deactivate()` inside your `tryNewLogin` method.

**Comment by TKalo** [comment]
I null-checked the singleton client value at the beginning of the app, and it is null so I cannot deactivate it there. That is also why I tried using a Provider instead of a singleton, in case it wasn't being destroyed along with the app.

The ideal would be to have a function run when the app is destroyed, where I can clean up the WebSocket. This of course is a functionality that should be provided by the Flutter framework, and not your library. However, subscriptions are still being handled by the StompClient after the app is closed, which must mean that not only the WebSocket survives, the StompClient also survives, despite not being programmatically accessible.

**Comment by KammererTob** [comment]
As far as i know Dart does not provide a way to determine if an instance is accessible or not. So it is your responsibility to disconnect/deactivate the client before it gets unaccessible

**Comment by TKalo** [comment]
I figured it out. When you rebuild a web app in your IDE, it doesn't destroy the old application, but it does build a new one. This is not apparent as there is still only one tab open in the browser and the print statements from both applications go into the same console window in the IDE making it appear as if messages from multiple applications are coming from the same one. This is only a problem when debugging in the IDE. When you refresh the page or close the tab in the browser manually, a normal cleanup of WebSockets occurs.
