### ISSUE TITLE
i can't connect over from http

### ISSUE THREAD

**Issue by gurkanucar** [blackhorse-one/stomp_dart_client#51]
Hello. i want to connect websocket over from http url. But it gives error:

WebSocketException: Unsupported URL scheme 'http'

what can i do? 
Thanks.

**Comment by KammererTob** [comment]
Hey,

this library currently only supports ws or wss as scheme (same as the [WebSocket ](https://api.dart.dev/stable/2.12.3/dart-html/WebSocket-class.html) class). We might add a way to detect http/https in the future to automatically upgrade the connection.

**Comment by gurkanucar** [comment]
Is there any way use the http spring boot stomp socket?

**Comment by KammererTob** [comment]
Is it possible that you are using SockJS? We are using Spring Boot Stomp ourselves and can connect via ws/wss just fine. If you are not using SockJS, can you maybe share your config?

**Comment by gurkanucar** [comment]
Of course.

This is my WSConfig file:

```
@Configuration
@EnableWebSocketMessageBroker
public class WsConfig implements WebSocketMessageBrokerConfigurer{

	@Override
	public void registerStompEndpoints(StompEndpointRegistry registry) {
		registry.addEndpoint("/javatechie").withSockJS();
	}
	
	@Override
	public void configureMessageBroker(MessageBrokerRegistry registry) {
		registry.enableSimpleBroker("/topic");
		registry.setApplicationDestinationPrefixes("/app");
	}
}
```

And this is my controller:

```
@Controller
public class ChatController {

	@MessageMapping("/chat.register")
	@SendTo("/topic/public")
	public ChatMessage register(@Payload ChatMessage chatMessage, SimpMessageHeaderAccessor headerAccessor) {
		headerAccessor.getSessionAttributes().put("username", chatMessage.getSender());
		return chatMessage;
	}

	@MessageMapping("/chat.send")
	@SendTo("/topic/public")
	public ChatMessage sendMessage(@Payload ChatMessage chatMessage) {
		return chatMessage;
	}

}
```

**Comment by gurkanucar** [comment]
wss or ws url not working on spring boot

**Comment by KammererTob** [comment]
`.withSockJS();`. You are using SockJS with Spring. Can you try if using `StompConfig.SockJS(..)` fixes the problem for you?

**Comment by gurkanucar** [comment]
Many thanks. I am taking "errno = 111" , but i think its because of my spring config.
