### ISSUE TITLE
webSocketError callback is not fire in flutter web 

### ISSUE THREAD

**Issue by asppdeo** [blackhorse-one/stomp_dart_client#53]
StompClient client = StompClient(
    config: StompConfig(
        url: 'wss://yourserver',
        onConnect: onConnectCallback,
          onWebSocketError: onWebSocketError,

    )
);

I am getting the connection error in the browser but not able to catch so not able to take any action on those cases please help me.

Note:-       _channel = await platform.connect(config);
may be it will help to find the issue on above platform.connect() methos has some issue

**Comment by KammererTob** [comment]
Hey. 

thanks for the report. I think this is an issue which was left open after the version 0.3.4 rework:

> Catch WebSocketChannelException to be platform agnostic (Note: this does not work for HTML yet)

I have now finally come around to fix this for Web aswell and i will publish a new version soon.

**Comment by KammererTob** [comment]
Fixed in version 0.4.2 (which i just published). Please let me know if this does still not work for you.
