### ISSUE TITLE
unable to subscribe

### ISSUE THREAD

**Issue by harshup20** [blackhorse-one/stomp_dart_client#55]
successfully connected to the server, but unable to subscribe to the topic as it looping into the timer function and continuously printing 'i am in timer' added my sort of code please guide me the right path
```
void onConnect(StompFrame frame) {
  stompClient.subscribe(
    destination: '/topic/messages/chatName',
    callback: (frame) {
      print('I am in callback of the subscription');
      List<dynamic>? result = json.decode(frame.body!);
      print(result);
    },
  );
  Timer.periodic(Duration(seconds: 5), (_) {
    print('i am in timer');
    stompClient.send(
      destination: '/app/chat.send',
      body: json.encode({'aa': "123",}),
    );
  });
}
```

**Comment by KammererTob** [comment]
Hey,

How does your server code look like? Specifically the subscription endpoint? And how do you send messages to the subscribers?

**Comment by KammererTob** [comment]
I will close this issue because of inactivity. Feel free to reopen if this isn't resolved.
