### ISSUE TITLE
How to pass clientID and username etc to authenticate and do durable subscriptions

### ISSUE THREAD

**Issue by noorkhan-92** [blackhorse-one/stomp_dart_client#59]
### How I can do durable subscriptions of topic and make the sending messages persistent
As Javascript has the following connect method to supply login and passcode etc.
```
client.connect(login, passcode, connectCallback);
  client.connect(login, passcode, connectCallback, errorCallback);
  client.connect(login, passcode, connectCallback, errorCallback, closeEventCallback);
  client.connect(login, passcode, connectCallback, errorCallback, closeEventCallback, host);
```
**especially i want to know how the message broker will authenticate the client. and how to do durable subscriptions and message persistent.**
[https://activemq.apache.org/how-do-durable-queues-and-topics-work](https://activemq.apache.org/how-do-durable-queues-and-topics-work)

**Comment by KammererTob** [comment]
Hey,

Regarding login/passcode: You can pass those via `stompConnectHeaders` . The Javascript library you are referring to is exactly doing that (see: https://stomp.github.io/stomp-specification-1.2.html#CONNECT_or_STOMP_Frame).

The link you posted is mainly describing the server part of durable subscriptions as far as i can see. What exactly are you expecting from this library for that? We are currently only implementing the STOMP Protocol as described here: https://stomp.github.io/stomp-specification-1.2.html

Hope this helps.

**Comment by KammererTob** [comment]
I will close this issue. If you still have questions or problems feel free to reopen.
