### ISSUE TITLE
WebSocketException: Connection to 'xxx' was not upgraded to websocket

### ISSUE THREAD

**Issue by mrm2004** [blackhorse-one/stomp_dart_client#62]
when trying to connect to the server, I'm getting this error "WebSocketException: Connection to 'http://localhost:8080/talk/ws-chat/#' was not upgraded to websocket", can anyone tell me what to do, if is it a problem in the app or on the server side?

**Comment by KammererTob** [comment]
Hey,

Can you post some of your client code? But this looks more like a server-side issue than with the client.

**Comment by KammererTob** [comment]
I am going to close this issue. If you are still facing issues feel free to reopen.

**Comment by SkyPrince77** [comment]
> Hey,
> 
> Can you post some of your client code? But this looks more like a server-side issue than with the client.

bro can you help me to solve the websocket issue in stomp dart client package
