### ISSUE TITLE
🐛 [Web] `webSocketConnectHeaders` headers not sent to Server on `CONNECT`

### ISSUE THREAD

**Issue by henry2man** [blackhorse-one/stomp_dart_client#63]
I have the following `StompClient` initialization code. 

```dart
StompClient _stompClient = StompClient(
        config: StompConfig.SockJS(
      url: socketUrl,
      webSocketConnectHeaders: {"Authorization": "Bearer <JWT Token here>"},
      onConnect: (frame) {
        print("Connected");
      },
      onWebSocketError: (error) =>
         print("Error");
    ));
```

I need to send an `Authorization` header in the `CONNECT` message in order to authenticate the request against backend.

When I use this code with Flutter Desktop for MacOS the headers are properly sent to the server and the request can be authenticated.

But using the same code and compiling the app for Flutter for Web, the header is not sent to the server.

Is this a package issue? Maybe I'm forgetting something different ?

**Comment by KammererTob** [comment]
Hey,

that is weird. The headers are part of the Stomp frame and thus should not be affected by the different WebSocket implementations of Web vs. Mobile vs. Desktop. Are the other headers of the `CONNECT` message there (accept-version and heart-beat)?

**Comment by henry2man** [comment]
@KammererTob I'll let you know this Monday, this is a blocking issue for me.

**Comment by KammererTob** [comment]
@henry2man I've just noticed that we may have been talking about different things. There are two types of connect headers in this library:

1. webSocketConnectHeaders: Those are used when the underlying WebSocket connection is established
2. stompConnectHeaders: Those are used inside the initial `CONNECT` frame of Stomp.

Judging from your example you probably are talking about 1.. Sadly the HTML WebSocket API has no way for me to pass any headers for connection request and thus this is probably why you don't see them. Your best bet in this case would be to include the Authorization token as part of the request URL (query parameter)

**Comment by henry2man** [comment]
@KammererTob  Ok, this makes a lot more sense.

After a bit of research I've found this two interesting resources that reflect these limitations:

From 
https://github.com/spring-projects/spring-framework/blob/main/src/docs/asciidoc/web/websocket.adoc#token-authentication: 

> The https://tools.ietf.org/html/rfc6455#section-10.5[WebSocket protocol, RFC 6455]
> "doesn't prescribe any particular way that servers can authenticate clients during
> the WebSocket handshake." In practice, however, browser clients can use only standard
> authentication headers (that is, basic HTTP authentication) or cookies and cannot (for example)
> provide custom headers. Likewise, the SockJS JavaScript client does not provide
> a way to send HTTP headers with SockJS transport requests. See
> https://github.com/sockjs/sockjs-client/issues/196[sockjs-client issue 196].
> Instead, it does allow sending query parameters that you can use to send a token,
> but that has its own drawbacks (for example, the token may be inadvertently
> logged with the URL in server logs).
> 
> NOTE: The preceding limitations are for browser-based clients and do not apply to the
> Spring Java-based STOMP client, which does support sending headers with both
> WebSocket and SockJS requests.

Here is another example of authenticating using query parameters: https://www.linode.com/docs/guides/authenticating-over-websockets-with-jwt/

Thanks

**Comment by KammererTob** [comment]
@henry2man Thanks for the resources for future readers. I will close this issue. If you have any other issue please feel free to reopen

**Comment by juanfactor88** [comment]
Hi @KammererTob I have the same issue except that I running on a mobile device, the headers are arriving empty (null) at the server so the authentication is not getting done. 

 void _connectToStomp(String url) async {
    //String? token = await getIt<StorageRepositoryService>().getToken();
    String token = 'dfadfdasfasdfasfasf';
    _stompClient = StompClient(
      config: StompConfig(
        url: url,
        stompConnectHeaders: {'Authorization': 'Bearer $token' ?? ""},
        webSocketConnectHeaders: {'Authorization': 'Bearer $token' ?? ""},
        onConnect: (StompFrame frame) {
          emit(const WebsocketState.DataReceived('Connected'));
          debugPrint(frame.body);
          _subscribeToTopic();
        },
        onWebSocketError: (error) {
          emit(WebsocketState.Error(error.toString()));
           debugPrint('----------------                -----------------');
          debugPrint(error.toString());
           debugPrint('----------------                -----------------');
        },
      ),
    );

    _stompClient!.activate();
  }

**Comment by juanfactor88** [comment]
> @juanfactor88 How does your server code look like?

@KammererTob this is my code.
```
@Configuration
@EnableWebSocket
@Slf4j
public class WebSocketConfig implements WebSocketConfigurer  {

    private final JsonWebTokenService jwtService;

    private final AccountManagerService accountManager;

    private final WebSocketService webSocketService;


    public WebSocketConfig(JsonWebTokenService jwtService, AccountManagerService accountManager, WebSocketService webSocketService) {
        this.jwtService = jwtService;
        this.accountManager = accountManager;
        this.webSocketService = webSocketService;
    }


    @Override
    public void registerWebSocketHandlers(WebSocketHandlerRegistry registry) {
        JwtHandshakeInterceptor handshakeInterceptor = new JwtHandshakeInterceptor(jwtService, accountManager, webSocketService);
        registry.addHandler(webSocketService, "/ws")
                .addInterceptors(handshakeInterceptor)
                .setAllowedOrigins("*");
    }

}
```

**Comment by KammererTob** [comment]
@juanfactor88 How does your JwtHandshakeInterceptor look? I've tried (although implementing another config interface in `WebSocketMessageBrokerConfigurer`), but in my interceptor the headers are present.

**Comment by KammererTob** [comment]
@juanfactor88 Hm. Not sure where/how you try to extract the authorization token from the headers, but normally you find it in `request.getHeaders()` here (i.e. `request.getHeaders().get('Authorization')`) . But be aware that this is case sensitive. Probably the better approach would be something like this:

```
        if (request instanceof ServletServerHttpRequest) {
            ((ServletServerHttpRequest) request).getServletRequest().getHeader("authorization");
        }
```

because `getHeader` is case insensitive (https://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpServletRequest.html#getHeader-java.lang.String-)
