### ISSUE TITLE
Incoming message with binary body

### ISSUE THREAD

**Issue by dlfk99** [blackhorse-one/stomp_dart_client#66]
Hi and thanks for the very nice package.

I'm using the package to connect to a Spring server. The server sends messages which have a binary body. I realised that the stomp_dart_client doesn't handle them (leads to an error and no StompFrame). I opened a PR with a possible solution to the problem. Could you have a look and let me know what you think about it?

Here is a description of the [PR](https://github.com/blackhorse-one/stomp_dart_client/pull/65) content (same as in the PR message):

If an incoming message has a certain content type the body should be treated as binary. The configuration allows to add content types as a list of Strings. A value of 'null' would treat missing 'content-type' headers as having a binary body (this behaviour is mentioned in the STOMP 1.1 spec).

The first commit changes the StompParser to treat a message with content type 'application/octet-stream' as having a binary body. This is needed when e.g. working with Spring (here a binaryBody leads to a 'content-type:application/octet-stream').

The second commit adds the possibility to configure content types which should lead to a StompFrame with a binary body. This allows more flexibility for different use cases.

**Comment by KammererTob** [comment]
Closed as https://github.com/blackhorse-one/stomp_dart_client/pull/65 was merged
