### ISSUE TITLE
How to implement an exponential reconnect backoff delay

### ISSUE THREAD

**Issue by RaulUrtecho** [blackhorse-one/stomp_dart_client#67]
I need increment the reconnection delay time exponentially lets say first try to connect 3000 ms, second try 6000 ms and so on.

But it seems not be possible with the current config parameter `reconnectDelay` which seems to be final value and therefore its value cannot be updated once the config is created.

Is there any way to implement that behavior or am I missing something here?

**Comment by KammererTob** [comment]
Hey,

at the moment this is not possible with the configurations supplied by this library. You could set the `reconnectDelay` to 0 and implement the reconnect logic yourself tho. For this you would probably need to listen to the appropiate callbacks `onWebSocketDone` and recreate the client everytime the delay changes.

Hope this helps. If you desperately need it inside this library i am happy to look at a PR, but i don't have the time to implement it myself at the moment.

**Comment by RaulUrtecho** [comment]
Oh I see, well I'd like to improve this, but time is not something I also have to spare, I think I will go to make the logic that recreates the client as you suggest. Thanks again there are few packages where their creators respond quickly.
