### ISSUE TITLE
supporting ws protocol 

### ISSUE THREAD

**Issue by mohammadshrahi** [blackhorse-one/stomp_dart_client#7]
Hello,
I'm trying to use this package with my project, and out web socket using ws protocol but unfortunatly
I was not able to connect.
I think support ws protocol it will be a big benefit. 
thanks

**Comment by KammererTob** [comment]
Hey,

can you give me an example snippet how you are trying to use this library? It should already be able to connect to ws:// urls. In fact i am using it myself locally like this:

```
_stompClient = StompClient(
    config: StompConfig(
        url: "ws://${config.stompHost}/messaging",
        connectionTimeout: Duration(milliseconds: 3000),
        stompConnectHeaders: {},
        beforeConnect: _beforeConnect,
        onConnect: _onConnect,
        onDisconnect: _onDisconnect,
        onWebSocketDone: _onWebSocketDone
     )
);
```

Do you get any errors?

Thanks!

**Comment by mohammadshrahi** [comment]
I'm using it like this
`    StompClient client = StompClient(
        config: StompConfig(
            url: 'ws://192.168.0.146:8088/websocket',
            onConnect: onConnectCallback,
            onWebSocketDone: () {
              print('onWebSocket done');
            },
            onWebSocketError: (dynamic err) {
              print(err);
            },
            onStompError: (frame) {
              print(frame.toString());
            }));
  }
  void onConnectCallback(StompClient client, StompFrame connectFrame) {
    // use the client object passed.
    print('connected');
  }
`
and all of this callbacks never calls

**Comment by KammererTob** [comment]
You also need to call `client.activate()` to start the connection process

**Comment by mohammadshrahi** [comment]
thanks, and sorry for late replay, yes it's working fine now
