### ISSUE TITLE
onConnect callback not triggered on android & ios

### ISSUE THREAD

**Issue by irufano** [blackhorse-one/stomp_dart_client#70]
### Step to reproduce:
1. Define callback outside the `initState`
2. Call `activate` on `initState`

### actual result :
- `onConnect` callback not triggered when connected, only `onDebugMessage` fired

### expected result
- `onConnect` triggered when connected and log `'Connected'` message

Heres my code:

```dart
void onConnectCallback(StompFrame connectFrame) {
    // client is connected and ready
    log('Connected');
  }

  @override
  void initState() {
    StompClient client = StompClient(
        config: StompConfig(
      url: 'wss://echo.websocket.events',
      beforeConnect: () async {
        log('waiting to connect...');
        await Future.delayed(const Duration(milliseconds: 200));
        log('connecting...');
      },
      onConnect: onConnectCallback,
      onDisconnect: (disconnectFRame) {
        log('disconnectFRame');
        log(disconnectFRame.command);
      },
      onDebugMessage: (message) {
        log(message);
      },
      onStompError: (errorFrame) {
        log('errorFrame');
        log(errorFrame.command);
      },
      onWebSocketError: (err) {
        log('Error');
        log(err.toString());
      },
    ));

    client.activate();
    super.initState();
  }
  ...
```

an here is the console message:

```bash
[log] waiting to connect...
[log] connecting...
[log] >>> CONNECT
      accept-version:1.0,1.1,1.2
      heart-beat:5000,5000
      
      
[log] <<< echo.websocket.events sponsored by Lob.com
[log] <<< CONNECT
      accept-version:1.0,1.1,1.2
      heart-beat:5000,5000
```

**Comment by KammererTob** [comment]
Hi,

the service you are using is echoing your websocket messages. It does not implement the Stomp protocol. It just echos your CONNECT request back to you, which the Stomp protocol will not recognize. A full connection is never established and that is why `onConnect` is not called.

**Comment by irufano** [comment]
I've change with my own ws and add stomp protocol to the service, and now `onConnect` triggred perfectly. Thankyou very much @KammererTob

**Comment by irufano** [comment]
> Hi,
> 
> the service you are using is echoing your websocket messages. It does not implement the Stomp protocol. It just echos your CONNECT request back to you, which the Stomp protocol will not recognize. A full connection is never established and that is why `onConnect` is not called.

I've change with my own ws and add stomp protocol to the service, and now onConnect triggered perfectly. Thankyou very much @KammererTob

**Comment by KammererTob** [comment]
Glad it works!
