### ISSUE TITLE
Need More Info

### ISSUE THREAD

**Issue by AliAkberAakash** [blackhorse-one/stomp_dart_client#71]
What do the functions `ack` and `nack` do?

**Comment by KammererTob** [comment]
Hi.

Please check the protocol documentation of STOMP:

https://stomp.github.io/stomp-specification-1.2.html#SUBSCRIBE_ack_Header
and further down!

Hope this helps. If you still have questions feel free to reopen.

**Comment by AliAkberAakash** [comment]
Hi, thanks this was helpful!
