### ISSUE TITLE
Having trouble with `subscribe` method's callback

### ISSUE THREAD

**Issue by AliAkberAakash** [blackhorse-one/stomp_dart_client#72]
Does the `callback` in the subscribe method need to be a top level function? I have tried with a class method it didn't work, but its working with a top level function. I couldn't find anything about this in the docs.

**Comment by KammererTob** [comment]
Hi,

normally it should work with any function. Can you show me some code where it isn't working and what the error is?

**Comment by AliAkberAakash** [comment]
Hi, thanks for responding, this is the code I'm using:
<script src="https://gist.github.com/AliAkberAakash/968466c090d4d529ce5b13b9e2c82d81.js"></script>

at line 62 when I'm using `_onDataReceived(frame.body)` which is a method of my class, this callBack never executes:
```
        _stompClient?.subscribe(
          destination: '/topic/umti/'+umti+'/status',
          callback: (StompFrame frame) {
            logger.d("Received stomp data from topic is: ${frame.body}");
           _onDataReceived(frame.body);
          },
        );
```

However, when I run the same code but with a top level method `onTokenData` it executes the callback.
```
_stompClient?.subscribe(
          destination: '/topic/umti/'+umti+'/status',
          callback: (StompFrame frame) {
            logger.d("Received stomp data from topic is: ${frame.body}");
            onTokenData(frame.body);
          },
        );
```

**Comment by AliAkberAakash** [comment]
`subscribeToClient` is called from another class.

**Comment by KammererTob** [comment]
Hi,

i've tried to reproduce your problem and was not able to do so. Here is my code and output:

Code:
```
class TestClass {
  late StompClient _client;

  void init() {
    _client = StompClient(
      config: StompConfig(
        url: 'ws://localhost:8080/messaging',
        onConnect: _onConnect,
        beforeConnect: () async {
          print('waiting to connect...');
          await Future.delayed(Duration(milliseconds: 200));
          print('connecting...');
        },
        onWebSocketError: (dynamic error) => print(error.toString()),
      ),
    );
    _client.activate();
  }

  void _onConnect(StompFrame frame) {
    _client.subscribe(
      destination: '/topic/public/judging/trends/32059/278010',
      callback: (frame) {
        List<dynamic>? result = json.decode(frame.body!);
        _onDataReceived(result);
      },
    );
  }

  void _onDataReceived(List<dynamic>? result) {
    print('Data received: ' + result.toString());
  }
}

void main() {
  // stompClient.activate();
  final clazz = TestClass();
  clazz.init();
}
```

Output:
```
$ dart example/main.dart
waiting to connect...
connecting...
Data received: []
Data received: [{a: 30.0, b: 3.0, c: 4, d: k}]
```

I would suggest you check your code for any issue as i am quite sure that isn't a problem directly with this library.

**Comment by AliAkberAakash** [comment]
Hi, 
I was able to resolve the issue, thanks for taking your time to help. 

I was getting an exception when trying to parse the frame data. I had put a log before the parsing but that line was not printing, thats why I got confused.
