### ISSUE TITLE
i can't send file which is 80k size base64encoded.

### ISSUE THREAD

**Issue by dizang2** [blackhorse-one/stomp_dart_client#8]
I tried to send a file which is  80k size base64encoded.

but failed with an onWebSocketDone event.

Is there any size limit ?

and do you have any suggetions ?

**Comment by KammererTob** [comment]
Hey,

the restriction is probably on the server side, which then drops your connection. I would suggest to increase the verbosity of logging on the server and then check there.
Also i would probably use the binaryBody for this, since base64 increases the size by about 37%.

**Comment by KammererTob** [comment]
I am going to close this issue. If you still have problems or questions feel free to open it again!
