### ISSUE TITLE
Deactivation Of The Connection

### ISSUE THREAD

**Issue by tjmeal** [blackhorse-one/stomp_dart_client#83]
Hello to everyone,

I have used you library successfully but i am facing a particular issue with the security/user.

a) Login to my app with userA > create a ws connection successfully everything works great.
b) When i log out from my app > i also call   stompClient.deactivate(); > i do get reply from the server <<< a["RECEIPT\nreceipt-id:disconnect-0\n\n\u0000"]
c) Now when i try to login with userB > on all my api calls the server identifies as logged in user the userB which is the correct > but all the web-sockets calls unidentify as logged in user userA.
d) If i do a a flutter hot restart ( and re initiate ws connection from scratch) everything works correct again.

What i understand is that when i log out and deactivate the connection (which i confirm also from my server) > somehow it keep the old jwtToken > and on new subscription under userB it uses the token of last connection uses the same headers that had on last connection instead of sending new ones ? I am suing the following way to access secure websocket connection. 

    onConnect: onConnect,
    webSocketConnectHeaders: {'Authorization': 'Bearer $_jwtToken'},

Do you have any solution on my problem ? 

Thanks in advance and i will be waiting for your reply.

**Comment by KammererTob** [comment]
Hi,

the instance of the client is probably still in memory and thus also the passed config (with the JWT of userA). You can access the config of the client anytime to make some changes. You need to change the `webSocketConnectHeaders` when logging in as a different user. Here is an example using the `onBeforeConnect` callback:

```
 _stompClient = StompClient(
      config: StompConfig(
        url: config.stompUrl,
        connectionTimeout: Duration(milliseconds: 3000),
        beforeConnect: _beforeConnect,
        onConnect: _onConnect,
        onDisconnect: _onDisconnect,
        onWebSocketDone: _onWebSocketDone,
      ),
  );
  .....
  Future<void> _beforeConnect() {
    return _authTokenRepository.getJWT().then((jwt) {
      _stompClient.config.webSocketConnectHeaders!['Authorization'] = 'Bearer ' + jwt!;
    });
  }
```

Another solution would be to completely re-create the client when another user logs in.
Hope this solves your issue.

**Comment by tjmeal** [comment]
Hello again and thanks a lot for your reply.

Yeap that does solve the issue.

One more problem? I have noticed (only in hot reloading thought) that some times i get a double connection to a channel.

I dont know if that possible to happen in prod environment or its only happening on hot reloading? 

Is there any way to make sure that i am subscribing only once ? Or limit the number of subscriptions ? Because we do know to how many channels we planning to subscribe. 

THanks i will be waiting your reply.

**Comment by KammererTob** [comment]
Hey,

this library does not track your active subscriptions and thus if a hot reload triggers a rerun of a function which subscribes (again) it just subscribes again. You probably want to track your subscriptions on your side (for example by using a Map with the paths you subscribed to), or make sure that a function is not rerun when the code re-renders. You also should probably test if it happens in production or not.

**Comment by tjmeal** [comment]
Hello,

Thats what i am planning to do, just wanted to make sure thats isn;t covered by the library.

Thanks again. !!
