### ISSUE TITLE
when flutter app is killed and re-open, the client doesn't return any message

### ISSUE THREAD

**Issue by nashihu** [blackhorse-one/stomp_dart_client#98]
i'm using this tool to debug my stomp server https://jxy.me/websocket-debug-tool/

after disconnect and reconnect, the server still gives message as expected

---

in my flutter app, i can connect and successfully getting messages

but there's a case when my app is killed and then open app and reconnect again, the client doesn't receive any message anymore

could you please try this case with your flutter example? thankyou

i'm using flutter 3.3.x and stomp 1.0.3

**Comment by KammererTob** [comment]
Hi,

you probably need to be a bit more specific. Can you please answer/provide the following:

- What do you mean "getting messages"? Do you mean the initial (welcome) messages on a subscription, or any other message that might have been sent to the subscription?
- What do you mean by "app is killed"? The app is force closed and then completely re-opend from a fresh state?
- Can you please provide the/some of the code you are using to connect/subscribe/handle the messages?

Thanks

**Comment by nashihu** [comment]
solved, there's a bug in my code not in stomp. thank you for reply
