### ISSUE TITLE
Connection erro

### ISSUE THREAD

**Issue by tariqarbi03** [blackhorse-one/stomp_dart_client#99]
This is my socket

    StompClient client =StompClient(
        config: StompConfig(
             url: 'wss://imtiaz.dev.dukanor.com/api/private/v1/websocket?auth_token=eyJhbGciOiJIUzUxMiJ9.eyJpbmZvIjoiNFkremNhOVRSd3pSS2J4cXNndk5IVlpzMFU4dXY0WHBNTElmcStLS1NaaWVWaElFU01wa1I1Kys4ZDJ0ejd6aVM0SHVYczJOZWVhb1pjc2M2TW5ucHRqM0dNRlF4N092NHBvcUc3dXNJR2ZNNFpPNmJ2cjVpaUNCdzdSZUxjT1g5NnVITlNwVDIya0JrWXZaWHhiY2RKbFRhNE9GRithcUhIeGVMZGZGVDB4REhWdlg2SnlULzZXM1lOZU5Ub1RpRE1jWEd6K2h4YXgxZG1zVTdPS1p3QjdHdkJqaUdxSmhrMVRyWDNBU1R0UTdKUTBCMzVjS1FEVGVid0llQyt5L2VoOG1ucFZmSW1DWDdwbUhMZ0ZRbVBFWWNFZUZ2cWk0Qk5uRjc1Y1ZSZ1V1VWlvZTBDRENBTUxQUEhyOGdZRHB5L2F1WE9lY1hWK01ra3N0QUgvdi8wSDVycjErdmNBSStQVm1WcWxkL2t6alBINDRRckpWWldLcmM4c2ZHQ0lqanZtcWdYSWVzRnFia2U0NTV0aGNKSk80VXYza2tjTUNrdU1OODlLT2pzT1c3YklUZEVrV3RlNUcyY3NWbG9uU05OY0pPdEd5Z1o5RWZjcGw5eWRwZXR3bUlJak9RNFVZKzd3TGRLYjkxeE55ZWpyUXZzK3JGeDdZOXQ2SC84QnRKbCt2WEc3eXV2cHh2Q0sxK3pTNnhJbWIyVVp6NGc2dkdWMXdmdmpCVTdkZnBNbTdwZnk3bThWb0REM2hQa04zRGhldjRvU0IvbGZuU0gyaWxWbVJWOHVYNzB3TC90VnkrZXluOXJINitQQzVmNDhndElkVDNoL3VGcXdPUEU4RjZYWXJQcjR3SU1MV3RhY1hyYkpPSXFpdm91WU9Lb2kwejRZK1J0cUVsOTJSU2RheEFNVUllazVxclpKL1NQL2U2V2czbWdjcUFheVhxUWh0UDFhbkZ0TldsQStrbkp6YWJYekw3RDRsaXQxSDlSVTgxTVBEWW5ZakhMOGMwNFBINUFJK2ZFeTBqZ0MrcG4wM2toR3BuZ1ZxRW1wMndQWi9aZ2JRNmU4MG9lYXdDdEcrdEg3RjFua0d0UFQ4SGNZQnlQNkp1Z1FJMUZHWGVXZlFCMENSa0E9PSIsInN1YiI6InRhcmlxYXJiaTAzQGdtYWlsLmNvbSIsImlhdCI6MTcwNjAwNDU2OSwiZXhwIjoxNzM3NTQwNTY5fQ.nqXY74SQcui_m8H9Vn5K1ZZBkkm1eK7GMHomNtkYrhLhOiC0mKLeujwv8aQLeAFbJrVVNm03QlzAB9ujJWhvow',
            onConnect: onConnect,
          onDisconnect: (disconnectFRame) {
            print('disconnectFRame');
            print(disconnectFRame.command);
          },
          onDebugMessage: (message) {
            print(message);
          },
          onStompError: (errorFrame) {
            print('errorFrame');
            print(errorFrame.command);
          },
          onWebSocketError: (err) {
            print('Error');
            print(err.toString());
          },
        ),
    );
    client.activate();
    print("Connecting");
    print("${client.isActive}");
    print("${client.connected}");
    print("done");

This error is 
Error
WebSocketChannelException: [object Event]
Connection error...reconnecting
Error
WebSocketChannelException: [object Event]
Connection error...reconnecting
Error
WebSocketChannelException: [object Event]
Connection error...reconnecting

**Comment by KammererTob** [comment]
This seems to be a SockJS endpoint and for me this returns 403 Forbidden. So maybe your auth_token is not correct?

**Comment by tariqarbi03** [comment]
![image](https://github.com/blackhorse-one/stomp_dart_client/assets/88434479/833f8ab1-34d3-409b-b0b1-e92baad9d5f5)
This is working on postman...
Token is working correctly

**Comment by tariqarbi03** [comment]
StompClient client =StompClient(
    config: StompConfig.SockJs(
         url: 'wss://imtiaz.dev.dukanor.com/api/private/v1/websocket?auth_token=eyJhbGciOiJIUzUxMiJ9.eyJpbmZvIjoiNFkremNhOVRSd3pSS2J4cXNndk5IVlpzMFU4dXY0WHBNTElmcStLS1NaaWVWaElFU01wa1I1Kys4ZDJ0ejd6aVM0SHVYczJOZWVhb1pjc2M2TW5ucHRqM0dNRlF4N092NHBvcUc3dXNJR2ZNNFpPNmJ2cjVpaUNCdzdSZUxjT1g5NnVITlNwVDIya0JrWXZaWHhiY2RKbFRhNE9GRithcUhIeGVMZGZGVDB4REhWdlg2SnlULzZXM1lOZU5Ub1RpRE1jWEd6K2h4YXgxZG1zVTdPS1p3QjdHdkJqaUdxSmhrMVRyWDNBU1R0UTdKUTBCMzVjS1FEVGVid0llQyt5L2VoOG1ucFZmSW1DWDdwbUhMZ0ZRbVBFWWNFZUZ2cWk0Qk5uRjc1Y1ZSZ1V1VWlvZTBDRENBTUxQUEhyOGdZRHB5L2F1WE9lY1hWK01ra3N0QUgvdi8wSDVycjErdmNBSStQVm1WcWxkL2t6alBINDRRckpWWldLcmM4c2ZHQ0lqanZtcWdYSWVzRnFia2U0NTV0aGNKSk80VXYza2tjTUNrdU1OODlLT2pzT1c3YklUZEVrV3RlNUcyY3NWbG9uU05OY0pPdEd5Z1o5RWZjcGw5eWRwZXR3bUlJak9RNFVZKzd3TGRLYjkxeE55ZWpyUXZzK3JGeDdZOXQ2SC84QnRKbCt2WEc3eXV2cHh2Q0sxK3pTNnhJbWIyVVp6NGc2dkdWMXdmdmpCVTdkZnBNbTdwZnk3bThWb0REM2hQa04zRGhldjRvU0IvbGZuU0gyaWxWbVJWOHVYNzB3TC90VnkrZXluOXJINitQQzVmNDhndElkVDNoL3VGcXdPUEU4RjZYWXJQcjR3SU1MV3RhY1hyYkpPSXFpdm91WU9Lb2kwejRZK1J0cUVsOTJSU2RheEFNVUllazVxclpKL1NQL2U2V2czbWdjcUFheVhxUWh0UDFhbkZ0TldsQStrbkp6YWJYekw3RDRsaXQxSDlSVTgxTVBEWW5ZakhMOGMwNFBINUFJK2ZFeTBqZ0MrcG4wM2toR3BuZ1ZxRW1wMndQWi9aZ2JRNmU4MG9lYXdDdEcrdEg3RjFua0d0UFQ4SGNZQnlQNkp1Z1FJMUZHWGVXZlFCMENSa0E9PSIsInN1YiI6InRhcmlxYXJiaTAzQGdtYWlsLmNvbSIsImlhdCI6MTcwNjAwNDU2OSwiZXhwIjoxNzM3NTQwNTY5fQ.nqXY74SQcui_m8H9Vn5K1ZZBkkm1eK7GMHomNtkYrhLhOiC0mKLeujwv8aQLeAFbJrVVNm03QlzAB9ujJWhvow',
        onConnect: onConnect,
      onDisconnect: (disconnectFRame) {
        print('disconnectFRame');
        print(disconnectFRame.command);
      },
      onDebugMessage: (message) {
        print(message);
      },
      onStompError: (errorFrame) {
        print('errorFrame');
        print(errorFrame.command);
      },
      onWebSocketError: (err) {
        print('Error');
        print(err.toString());
      },
    ),
);
client.activate();
print("Connecting");
print("${client.isActive}");
print("${client.connected}");
print("done");






This is working code...
